trigger:
- master
- release/*
- test-azure

jobs:
- job: Build
  variables:
  - group: wayland
  - name: TZ
    value: 'Europe/Oslo'
  - name: WIN_TZ
    value: 'W. Europe Standard Time'
  - name: NODE_VERSION
    value: 10.17.0
  strategy:
    matrix:
      linux:
        IMAGE_NAME: 'ubuntu-16.04'
      macOS:
        IMAGE_NAME: 'macos-10.13'
      win32:
        IMAGE_NAME: 'vs2017-win2016'
        ARCH: 'ia32'
        NODE_ARCH: '32'

  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - script: tzutil /s "$(WIN_TZ)"
    condition: contains(variables['IMAGE_NAME'], 'win')
    displayName: 'Fix Windows timezone'
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    condition: ne(variables['NODE_ARCH'], '32')
    displayName: 'Install Node.js $(NODE_VERSION)'
  - bash: |
      set -o errexit -o pipefail
      choco install -y nvm
      export PATH=$NVM_HOME:$PATH
      nvm install $(NODE_VERSION) $(NODE_ARCH)
      nvm use $(NODE_VERSION) $(NODE_ARCH)
      ln -sf "$NVM_SYMLINK/node" "$NODE_SYMLINK/node"
    env: {
      NVM_HOME: "/C/ProgramData/nvm",
      NVM_SYMLINK: "/C/ProgramData/nvm/v$(NODE_VERSION)",
      NODE_SYMLINK: "/C/Program Files/nodejs",
    }
    condition: and(contains(variables['IMAGE_NAME'], 'win'), eq(variables['NODE_ARCH'], '32'))
    displayName: 'Install Node.js $(NODE_VERSION) 32-bit'
  - bash: |
      set -o errexit -o pipefail
      sudo apt-get update
      sudo apt-get install libudev-dev
    condition: contains(variables['IMAGE_NAME'], 'ubuntu')
    displayName: 'Setup build environment for Linux'
  - bash: |
      set -o errexit -o pipefail
      npm i
      npm run lint
      npm run build
      npm test
    condition: not(contains(variables['IMAGE_NAME'], 'win'))
    displayName: 'Build on not windows'
  - bash: |
      set -o errexit -o pipefail
      npm i -g node-gyp@6.0.1
      npm config set node_gyp "C:\npm\prefix\node_modules\node-gyp\bin\node-gyp.js"
      npm i
      npm run lint
      npm run build
      npm test
    condition: contains(variables['IMAGE_NAME'], 'win')
    displayName: 'Build on windows'
  - bash: |
      sudo apt-get install icnsutils
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'ubuntu'))
    displayName: 'Setup release environment for Linux'
  - bash: |
      npx build -p never
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'ubuntu'))
    displayName: 'Release on Linux'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'NORDIC_SIGNING_CERTIFICATE.pfx'
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'win'))
    displayName: 'Donwload certificate on Windows'
  - script: |
      set CSC_LINK=$(Agent.TempDirectory)\NORDIC_SIGNING_CERTIFICATE.pfx
      set CSC_KEY_PASSWORD=$(NORDIC_SIGNING_CERTIFICATE_PASSWORD_PFX)
      npx build -p never
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'win'))
    displayName: 'Release on Windows'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'NORDIC_SIGNING_CERTIFICATE.p12'
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'mac'))
    displayName: 'Donwload certificate on macOS'
  - bash: |
      set -o errexit -o pipefail
      export CSC_LINK=$(Agent.TempDirectory)/NORDIC_SIGNING_CERTIFICATE.p12
      export CSC_KEY_PASSWORD=$(NORDIC_SIGNING_CERTIFICATE_PASSWORD_P12)
      npx build -p never
    condition: and(ne(variables['Build.Reason'], 'PullRequest'), contains(variables['IMAGE_NAME'], 'mac'))
    displayName: 'Release on macOS'
  - bash: |
      set -o errexit -o pipefail
      cp release/*.exe "$(Build.ArtifactStagingDirectory)" || :
      cp release/*.zip "$(Build.ArtifactStagingDirectory)" || :
      cp release/*.dmg "$(Build.ArtifactStagingDirectory)" || :
      cp release/*.tar.gz "$(Build.ArtifactStagingDirectory)" || :
      cp release/*.AppImage "$(Build.ArtifactStagingDirectory)" || :
      cp release/latest* "$(Build.ArtifactStagingDirectory)"
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Copy artifacts'
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'waylandCI'
      repositoryName: 'NordicSemiconductor/pc-nrfconnect-launcher'
      action: 'edit'
      tagSource: 'Git tag'
      tag: '$(Build.SourceBranchName)'
      assetUploadMode: 'replace'
      isDraft: 'true'
      addChangeLog: 'false'
    condition: ne(variables['Build.Reason'], 'PullRequest')
